### ISSUE TITLE
I could not get any camera image on the browser

### ISSUE THREAD

**Issue by egeozgul** [Inglebard/esp32cam-relay#1]
On the esp32 uart terminal, it printed the following line which shows that it connected to the server.

[WSc] Connected to url: /jpgstream_server
Image sent
Image sent

But I could not get any image on the browser.
I attached the blank html page.
I would appreciate if you could give a hint regarding what might be wrong.

![Untitled](https://user-images.githubusercontent.com/10923392/122689669-82b31f80-d1f2-11eb-8784-6215234064db.png)

**Comment by Inglebard** [comment]
Hi @egeozgul ,

You are using HTTP and not HTTPS what's why I suppose it is not working.
I just make a commit and hope it will works.
https://github.com/Inglebard/esp32cam-relay/commit/e3f0cea314811dfcd64f4146a8749c43d63b9682

If is still don't can you check your web console ? (F12 for firefox and chrome and refresh the page)

**Comment by egeozgul** [comment]
It worked! You're awesome!! Thank you for your work!

**Comment by Inglebard** [comment]
@egeozgul Nice, I close the issue.
